import { PageContainer, PageContent } from '@/styles/pages/Home'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Habits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <PageContainer>
      <PageContent>
        <h1>Hello world</h1>
      </PageContent>
     </PageContainer>
    </>
  )
}
